replicaCount: 1

image:
  repository: cozyruiz/intranet-nextjs
  tag: "1.7"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

monitoring:
  enabled: false

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - secretName: escalante-wildcard-tls
      hosts:
        - intranet-nextjs-dev.escalante.com.mx
  hosts:
    - host: intranet-nextjs-dev.escalante.com.mx
      paths:
        - path: /
          pathType: Prefix
