replicaCount: 1

image:
  repository: cozyruiz/intranet-nextjs
  tag: "1.7"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nextjs.local
      paths:
        - path: /
          pathType: Prefix