replicaCount: 1

image:
  repository: cozyruiz/intranet-nextjs
  tag: "1.1"
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nextjs.prod
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: production
  ENVIRONMENT: "PROD"