replicaCount: 1

image:
  repository: cozyruiz/intranet-nextjs
  tag: "latest"
  pullPolicy: Always

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tls:
    - secretName: escalante-wildcard-tls
      hosts:
        - intranet-nextjs-dev.escalante.com.mx
  hosts:
    - host: intranet-nextjs-dev.escalante.com.mx
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: development
  ENVIRONMENT: "DEV"
  NEXT_PUBLIC_ENVIRONMENT: "DEV"

envSecretName: intranet-nextjs-dev-env

monitoring:
  enabled: true
