replicaCount: 1

image:
  repository: cozyruiz/intranet-nextjs
  tag: "latest"
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: nextjs.prod
      paths:
        - path: /
          pathType: Prefix

env:
  NODE_ENV: production
  ENVIRONMENT: "PROD"
  NEXT_PUBLIC_ENVIRONMENT: "PROD"